import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { technicianApi } from "../api/technicianApi";
import type { RequestView } from "../types/technician";

type Props = { jobs: RequestView[]; onBack: () => void };
export default function PartsScreen({ jobs, onBack }: Props) {
  const [parts, setParts] = useState<any[]>([]), [requests, setRequests] = useState<any[]>([]), [cart, setCart] = useState<Record<string, number>>({});
  const [query, setQuery] = useState(""), [serviceRequestId, setServiceRequestId] = useState<number | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const load = async () => { setLoading(true); try { const [catalog, history] = await Promise.all([technicianApi.parts({ q: query }), technicianApi.partRequests()]); setParts(catalog.items || []); setRequests(history.items || []); } catch (error) { setMessage(error instanceof Error ? error.message : "Parts are unavailable."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => parts.filter(part => !query || `${part.name} ${part.sku} ${part.categoryName}`.toLowerCase().includes(query.toLowerCase())), [parts, query]);
  const count = Object.values(cart).reduce((total, value) => total + value, 0);
  const submit = async () => { if (!serviceRequestId || !count) { setMessage("Choose a job and add at least one part."); return; } setBusy(true); try { await technicianApi.submitPartRequest({ serviceRequestId, notes: "Requested from Technician Parts", lines: Object.entries(cart).map(([partItemId, quantity]) => ({ partItemId: Number(partItemId), quantity })) }); setCart({}); setMessage("Parts request submitted."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not submit parts request."); } finally { setBusy(false); } };
  return <View style={s.screen}><View style={s.header}><Pressable onPress={onBack} accessibilityLabel="Back" style={s.icon}><Ionicons name="arrow-back" size={22} color="#082A55" /></Pressable><View style={s.flex}><Text style={s.title}>Parts / Spare Parts</Text><Text style={s.subtitle}>Request stock for an active service job.</Text></View><Pressable onPress={() => void load()} accessibilityLabel="Refresh" style={s.icon}><Ionicons name="refresh" size={21} color="#246DE3" /></Pressable></View><ScrollView contentContainerStyle={s.content}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={() => void load()} placeholder="Search parts or SKU" style={s.search} /><Text style={s.label}>Relevant service request</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{jobs.filter(job => !["COMPLETED", "CANCELLED"].includes(job.status)).map(job => <Pressable key={job.id} onPress={() => setServiceRequestId(job.id)} style={[s.chip, serviceRequestId === job.id && s.selected]}><Text style={[s.chipText, serviceRequestId === job.id && s.selectedText]}>{job.serviceId || `Job #${job.id}`}</Text></Pressable>)}</ScrollView>{message ? <Text style={s.message}>{message}</Text> : null}<Text style={s.heading}>Available parts</Text>{loading ? <ActivityIndicator color="#246DE3" /> : visible.map(part => <View key={part.id} style={s.card}><View style={s.flex}><Text style={s.partName}>{part.name}</Text><Text style={s.meta}>{part.sku} · {part.categoryName} · {part.unit}</Text><Text style={s.meta}>{part.available ? `${part.quantityOnHand} available` : "Out of stock"}</Text></View><View style={s.quantity}><Pressable disabled={!part.available} onPress={() => setCart(current => ({ ...current, [part.id]: Math.max(0, (current[part.id] || 0) - 1) }))}><Text style={s.step}>-</Text></Pressable><Text style={s.number}>{cart[part.id] || 0}</Text><Pressable disabled={!part.available || (cart[part.id] || 0) >= part.quantityOnHand} onPress={() => setCart(current => ({ ...current, [part.id]: (current[part.id] || 0) + 1 }))}><Text style={s.step}>+</Text></Pressable></View></View>)}<View style={s.summary}><Text style={s.heading}>Request summary</Text><Text style={s.meta}>{count} item(s) selected</Text><Pressable disabled={busy || !count || !serviceRequestId} onPress={() => void submit()} style={[s.submit, (!count || !serviceRequestId) && s.disabled]}><Text style={s.submitText}>{busy ? "Submitting..." : "Submit parts request"}</Text></Pressable></View><Text style={s.heading}>Request history</Text>{requests.map(request => <View key={request.id} style={s.history}><Text style={s.partName}>Request #{request.id} · {request.status}</Text><Text style={s.meta}>Service #{request.serviceRequestId} · {(request.lines || []).map((line: any) => `${line.itemName} x${line.requestedQuantity}`).join(", ")}</Text></View>)}</ScrollView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#F6F8FB"},header:{minHeight:64,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:10,backgroundColor:"#FFFFFF",borderBottomWidth:1,borderColor:"#DDE5EF"},content:{padding:16,gap:12,paddingBottom:40},flex:{flex:1},icon:{width:44,height:44,alignItems:"center",justifyContent:"center"},title:{fontSize:20,fontWeight:"700",color:"#082A55"},subtitle:{fontSize:13,color:"#66758A"},search:{minHeight:50,borderWidth:1,borderColor:"#DDE5EF",borderRadius:12,backgroundColor:"#FFFFFF",paddingHorizontal:14,color:"#102033"},label:{fontSize:13,fontWeight:"700",color:"#102033"},chips:{gap:8},chip:{paddingHorizontal:14,paddingVertical:10,borderRadius:20,backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#DDE5EF"},selected:{backgroundColor:"#082A55",borderColor:"#082A55"},chipText:{color:"#66758A"},selectedText:{color:"#FFFFFF"},message:{padding:12,borderRadius:10,backgroundColor:"#EAF2FF",color:"#246DE3"},heading:{fontSize:17,fontWeight:"700",color:"#082A55"},card:{padding:14,borderRadius:14,backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#DDE5EF",flexDirection:"row",gap:12},partName:{fontSize:15,fontWeight:"700",color:"#102033"},meta:{fontSize:12,color:"#66758A",marginTop:4},quantity:{flexDirection:"row",alignItems:"center",gap:12},step:{fontSize:22,color:"#246DE3"},number:{fontSize:16,fontWeight:"700",color:"#102033"},summary:{padding:16,borderRadius:14,backgroundColor:"#EAF7EF",gap:8},submit:{minHeight:48,borderRadius:12,backgroundColor:"#168A4A",alignItems:"center",justifyContent:"center"},submitText:{color:"#FFFFFF",fontWeight:"700"},disabled:{opacity:.45},history:{padding:12,borderBottomWidth:1,borderColor:"#DDE5EF"}});
