import { Platform, StatusBar, StyleSheet } from "react-native";

export const colors = {
  background: "#F6F8FB",
  surface: "#FFFFFF",
  text: "#102033",
  muted: "#66758A",
  primary: "#082A55",
  action: "#168A4A",
  info: "#246DE3",
  teal: "#0F766E",
  border: "#DDE5EF",
  danger: "#D64545",
  warn: "#D9901A",
  yellow: "#F6A800",
};
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background, paddingTop: Platform.OS === "android" ? StatusBar.currentHeight ?? 0 : 0 },
  app: { flex: 1, width: "100%", maxWidth: 1040, alignSelf: "center", minHeight: 0 },
  center: { flex: 1, justifyContent: "center", padding: 24, gap: 14 },
  header: {
    height: 56,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerButton: { width: 60, minHeight: 44, alignItems: "center", justifyContent: "center" },
  headerIconButton: { borderRadius: 22 },
  logo: {
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 3,
    color: colors.primary,
  },
  content: { padding: 16, paddingBottom: 24, gap: 16 },
  contentFill: { flex: 1, minHeight: 0, padding: 16, paddingBottom: 16 },
  pageHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 8,
  },
  refreshButton: { minHeight: 48, justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.info,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  refreshText: { fontSize: 12, color: colors.info, fontWeight: "700" },
  listContent: { paddingBottom: 12 },
  kicker: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
    letterSpacing: 1,
  },
  title: { fontSize: 24, lineHeight: 32, color: colors.text, fontWeight: "700", marginBottom: 6 },
  sectionHeading: {
    fontSize: 17,
    color: colors.text,
    fontWeight: "700",
    marginVertical: 8,
  },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  link: { color: colors.primary, fontWeight: "600" },
  banner: {
    backgroundColor: "#FFF3E8",
    padding: 16,
    borderBottomWidth: 1,
    borderColor: "#FFD9B8",
  },
  errorText: { color: colors.danger, lineHeight: 20 },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginVertical: 12,
  },
  metric: {
    width: "31%",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
  },
  metricValue: { fontSize: 25, color: colors.primary, fontWeight: "700" },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  cardTitle: { fontSize: 16, lineHeight: 23, color: colors.text, fontWeight: "600", marginBottom: 5 },
  row: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  rowText: { color: colors.text, flex: 1 },
  rowBetween: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", alignItems: "flex-start", gap: 8 },
  checkRow: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  checkBox: {
    width: 44,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  checkCopy: { flex: 1, minWidth: 0 },
  empty: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    marginVertical: 8,
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#EAF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  emptyTitle: { color: colors.primary, fontSize: 16, fontWeight: "600", marginBottom: 4 },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "#E2F1EF",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeDanger: { backgroundColor: "#F9E0E0" },
  badgeMuted: { backgroundColor: "#ECEFF2" },
  badgeText: { color: colors.primary, fontSize: 11, lineHeight: 16, fontWeight: "500" },
  jobsContent: { padding: 20, paddingBottom: 32, gap: 16, width: "100%", maxWidth: 760, alignSelf: "center" },
  jobsIntro: { gap: 6 },
  jobsDescription: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  jobsSearchField: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 16, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface },
  jobsSearchText: { flex: 1, minWidth: 0, minHeight: 50, fontSize: 15, color: colors.text, paddingVertical: 12 },
  jobsFilters: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 16, gap: 20 },
  jobsFilterGroup: { gap: 10 },
  jobsFilterLabel: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "600" },
  jobsFilterChip: { minHeight: 44, borderRadius: 999, paddingHorizontal: 14, backgroundColor: "#F6F8FB" },
  jobsFilterSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  jobsFilterText: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: "500" },
  jobsFilterSelectedText: { color: colors.surface, fontWeight: "600" },
  jobsResultsRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 8, paddingTop: 4 },
  jobsResultsTitle: { color: colors.primary, fontSize: 18, lineHeight: 26, fontWeight: "700" },
  jobsResultCount: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  jobsBuildingThumb: { width: 52, height: 52, borderRadius: 14, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" },
  jobsService: { flexDirection: "row", alignItems: "center", gap: 8, flexGrow: 1, flexShrink: 1, flexBasis: 160 },
  jobsStatusBadge: { alignSelf: "flex-start", maxWidth: "100%", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, backgroundColor: "#EAF2FF" },
  jobsStatusText: { color: colors.primary, fontSize: 12, lineHeight: 18, fontWeight: "600" },
  jobsStatusSuccess: { backgroundColor: "#EAF7EF" },
  jobsStatusSuccessText: { color: colors.action },
  jobsStatusEmergency: { backgroundColor: "#FFF0F0" },
  jobsStatusEmergencyText: { color: colors.danger },
  jobHeader: { gap: 20, marginBottom: 0 },
  jobStatusRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 8 },
  filterWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  filterWrappedItem: { marginRight: 0, minHeight: 40, borderRadius: 10 },
  filters: { minHeight: 44, maxHeight: 48, marginBottom: 10 },
  filter: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    marginRight: 8,
    backgroundColor: colors.surface,
  },
  selected: { borderColor: colors.info, backgroundColor: "#EAF2FF" },
  primaryButton: { minHeight: 48, justifyContent: "center",
    backgroundColor: colors.primary,
    borderRadius: 999,
    padding: 14,
    alignItems: "center",
    marginVertical: 5,
  },
  dangerButton: { minHeight: 48, justifyContent: "center",
    backgroundColor: colors.danger,
    borderRadius: 10,
    padding: 14,
    alignItems: "center",
    marginVertical: 5,
  },
  outlineButton: { minHeight: 48, justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 999,
    padding: 13,
    alignItems: "center",
    marginVertical: 5,
  },
  primaryText: { color: colors.surface, fontSize: 14, lineHeight: 20, fontWeight: "600" },
  outlineText: { color: colors.primary, fontSize: 13, lineHeight: 19, fontWeight: "500" },
  disabled: { opacity: 0.5 },
  danger: { color: colors.danger },
  nav: { flexDirection: "row", flexShrink: 0, minHeight: 76, paddingVertical: 8, backgroundColor: colors.surface, borderTopWidth: 1, borderColor: colors.border },
  navItem: { flex: 1, minWidth: 0, minHeight: 48, alignItems: "center", justifyContent: "center", gap: 4 },
  navIcon: {
    fontSize: 20,
    color: colors.muted,
    textAlign: "center",
    fontWeight: "700",
  },
  navBadge: { position: "absolute", top: -7, right: -12, minWidth: 20, borderRadius: 10, paddingHorizontal: 3, backgroundColor: colors.danger, color: colors.surface, fontSize: 12, lineHeight: 18, textAlign: "center" },
  navText: { fontSize: 12, color: colors.muted, fontWeight: "700" },
  navActive: { color: colors.primary },
  inputGroup: { gap: 5, marginBottom: 8 },
  inputLabel: { fontSize: 13, lineHeight: 20, color: colors.muted, fontWeight: "500" },
  input: { minHeight: 48, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: colors.text },
  textarea: { minHeight: 78, textAlignVertical: "top" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(6,18,38,0.64)",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modal: {
    backgroundColor: colors.surface,
    paddingTop: 10,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: "92%",
    width: "100%",
    maxWidth: 620,
    overflow: "hidden",
  },
  sheetHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: "#CED8E5", alignSelf: "center", marginBottom: 12 },
  sheetHero: { marginHorizontal: 16, padding: 22, borderRadius: 22, gap: 10 },
  sheetHeroTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  sheetIcon: { width: 46, height: 46, backgroundColor: "#FFFFFF14", borderWidth: 1, borderColor: "#FFFFFF24", borderRadius: 15, alignItems: "center", justifyContent: "center" },
  sheetEyebrow: { flex: 1, color: "#B9D5F6", fontSize: 10, lineHeight: 16, letterSpacing: 1.2, fontWeight: "700" },
  sheetClose: { minWidth: 44, minHeight: 44, alignItems: "center", justifyContent: "center" },
  sheetTitle: { color: colors.surface, fontSize: 24, lineHeight: 32, fontWeight: "700", letterSpacing: -0.5 },
  sheetDescription: { color: "#C6D8ED", fontSize: 13, lineHeight: 21 },
  sheetForm: { padding: 24, gap: 18 },
  sheetField: { gap: 10 },
  sheetInput: { minHeight: 54, borderWidth: 1, borderColor: colors.border, borderRadius: 16, backgroundColor: colors.background, padding: 16, color: colors.text, fontSize: 15, lineHeight: 22 },
  sheetTextarea: { minHeight: 126, textAlignVertical: "top" },
  sheetActions: { flexDirection: "row", flexWrap: "wrap", gap: 12, paddingHorizontal: 24, paddingTop: 16, paddingBottom: 28, borderTopWidth: 1, borderTopColor: "#E8EEF5", backgroundColor: colors.surface },
  sheetCancel: { flexGrow: 1, flexBasis: 90, minHeight: 54, borderRadius: 999, borderWidth: 1, borderColor: colors.border, padding: 14, alignItems: "center", justifyContent: "center" },
  sheetSubmit: { flexGrow: 2, flexBasis: 160, minHeight: 54, borderRadius: 999, backgroundColor: colors.primary, padding: 14, flexDirection: "row", gap: 10, alignItems: "center", justifyContent: "center" },
  workPanel: { backgroundColor: colors.surface, borderRadius: 24, padding: 22, borderWidth: 1, borderColor: colors.border, gap: 16 },
  panelEyebrow: { color: colors.muted, fontSize: 10, lineHeight: 16, fontWeight: "700", letterSpacing: 1.2 },
  panelFieldLabel: { color: colors.primary, fontSize: 13, lineHeight: 20, fontWeight: "600" },
  panelTag: { backgroundColor: "#EFF4F8", color: colors.muted, fontSize: 11, lineHeight: 17, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6 },
  verificationIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" },
  verificationResend: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 8, alignSelf: "flex-start", paddingVertical: 8 },
  verificationCode: { minHeight: 64, borderRadius: 16, borderWidth: 1, borderColor: "#B9CFEF", backgroundColor: "#F6F9FF", color: colors.primary, fontSize: 22, letterSpacing: 5, textAlign: "center", paddingHorizontal: 16, paddingVertical: 16, fontWeight: "600" },
  checklistEmpty: { padding: 16, borderRadius: 16, backgroundColor: colors.background },
  checklistHeading: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 10, justifyContent: "space-between" },
  checklistChecked: { backgroundColor: colors.primary, borderColor: colors.primary },
  actions: { flexDirection: "row", gap: 10 },
  attachmentActions: { flexDirection: "row", gap: 8, marginVertical: 10 },
  selectedFile: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  homeContent: {
    padding: 16,
    paddingBottom: 92,
    gap: 10,
    backgroundColor: colors.background,
  },
  homeTop: {
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconButton: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center" },
  valorMark: { flexDirection: "row", alignItems: "center", gap: 7 },
  valorV: { color: colors.yellow, fontSize: 28, fontWeight: "700" },
  logoSub: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
    marginTop: -2,
  },
  homeTopActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  homeIcon: { fontSize: 18, color: colors.primary },
  iconBadge: {
    position: "absolute",
    right: 0,
    top: 0,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: colors.danger,
    color: colors.surface,
    fontSize: 12,
    textAlign: "center",
    lineHeight: 15,
    fontWeight: "700",
  },
  avatarCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FFE5BE",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.primary,
  },
  homeAvatar: { fontSize: 20 },
  heroCard: {
    minHeight: 150,
    backgroundColor: colors.primary,
    borderRadius: 10,
    padding: 14,
    flexDirection: "row",
    overflow: "hidden",
  },
  heroCopy: { flex: 1, zIndex: 2 },
  heroKicker: { fontSize: 12, color: "#DDE5EF" },
  heroTitle: {
    fontSize: 19,
    color: colors.surface,
    fontWeight: "700",
    marginTop: 4,
  },
  heroMeta: { fontSize: 12, color: "#DDE5EF", marginTop: 4 },
  availability: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
  },
  availabilityDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.action,
  },
  availabilityText: { fontSize: 12, color: colors.action, fontWeight: "600" },
  availabilityChevron: { fontSize: 13, color: colors.muted },
  heroServiceBox: {
    position: "absolute",
    right: 10,
    top: 28,
    width: 48,
    padding: 5,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,0.09)",
  },
  heroServiceText: {
    color: colors.surface,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  techIllustration: {
    width: 116,
    alignItems: "center",
    justifyContent: "flex-end",
    position: "relative",
  },
  techHead: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#F6C79A",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 7,
    borderColor: "#0B2347",
  },
  techFace: { color: "#1B3152", fontSize: 12 },
  techBody: {
    width: 72,
    height: 58,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "#12345F",
    alignItems: "center",
    justifyContent: "center",
  },
  techBadge: { color: colors.yellow, fontSize: 20, fontWeight: "700" },
  techThumb: {
    position: "absolute",
    right: 2,
    bottom: 34,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.yellow,
    alignItems: "center",
    justifyContent: "center",
  },
  homeMetrics: { flexDirection: "row", gap: 10, paddingRight: 16 },
  homeMetric: {
    width: 120,
    minHeight: 126,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  homeMetricIcon: { color: colors.info, fontSize: 19, fontWeight: "700" },
  homeMetricTeal: { color: colors.teal },
  homeMetricAmber: { color: colors.warn },
  homeMetricRed: { color: colors.danger },
  homeMetricGreen: { color: colors.action },
  homeMetricValue: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: "700",
    marginTop: 2,
  },
  homeMetricLabel: {
    color: colors.muted,
    fontSize: 12,
    textAlign: "center",
    lineHeight: 17,
    marginTop: 3,
  },
  homeSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
  },
  homeSectionTitle: { fontSize: 18, color: colors.primary, fontWeight: "700" },
  homeViewAll: { color: colors.info, fontSize: 12, fontWeight: "600" },
  homeViewAllButton: { flexDirection: "row", alignItems: "center", gap: 2, minHeight: 32 },
  homeJobRow: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    minHeight: 76,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  jobTime: { fontSize: 12, color: colors.primary, fontWeight: "700", width: 58 },
  homeJobCopy: { flex: 1, minWidth: 0 },
  homeJobTitle: { fontSize: 14, color: colors.primary, fontWeight: "700" },
  homeJobMeta: { fontSize: 12, color: colors.muted, marginTop: 4 },
  homeDualRow: { flexDirection: "row", gap: 8 },
  emergencyCard: {
    flex: 1,
    minHeight: 70,
    backgroundColor: "#FFF0F0",
    borderRadius: 8,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  supportCard: {
    flex: 1,
    minHeight: 70,
    backgroundColor: "#EAF2FF",
    borderRadius: 8,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dualIcon: { fontSize: 23 },
  dualCopy: { flex: 1, minWidth: 0 },
  dualTitle: { fontSize: 14, color: colors.primary, fontWeight: "700" },
  dualText: { fontSize: 12, color: colors.muted, lineHeight: 17, marginTop: 2 },
  quickGrid: { flexDirection: "row", gap: 7 },
  quickAction: {
    flex: 1,
    minHeight: 72,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  quickIcon: { color: colors.info, fontSize: 16, fontWeight: "700" },
  quickIconRed: { color: colors.danger },
  quickIconGreen: { color: colors.action },
  quickIconAmber: { color: colors.warn },
  quickLabel: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
    textAlign: "center",
  },
  safetyCard: {
    backgroundColor: "#EAF7EF",
    borderRadius: 8,
    padding: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 4,
  },
  safetyIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#C6EED5",
    color: colors.action,
    textAlign: "center",
    lineHeight: 34,
    fontWeight: "700",
    fontSize: 19,
  },
  safetyCopy: { flex: 1 },
  safetyTitle: { fontSize: 12, color: colors.primary, fontWeight: "700" },
  safetyText: {
    fontSize: 12,
    color: colors.muted,
    lineHeight: 17,
    marginTop: 2,
  },
  chevron: { fontSize: 20, color: colors.muted },
  jobsTitle: { fontSize: 24, lineHeight: 32, color: colors.primary, fontWeight: "700" },
  datePicker: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  dateIcon: { color: colors.info, fontSize: 15, marginRight: 8 },
  dateText: { flex: 1, color: colors.primary, fontSize: 12, fontWeight: "600" },
  subFilterRow: { flexDirection: "row", gap: 8, marginBottom: 10 },
  jobSearch: {
    height: 48,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  jobSearchInput: { flex: 1, height: 46, color: colors.text, fontSize: 15 },
  subFilterInput: {
    flex: 1,
    height: 38,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    color: colors.text,
    fontWeight: "600",
  },
  assignedCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 9,
    marginBottom: 8,
    flexDirection: "row",
    gap: 9,
  },
  assignedVisual: {
    width: 72,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF2FF",
    borderRadius: 7,
    padding: 6,
  },
  assignedService: {
    fontSize: 12,
    color: colors.primary,
    textAlign: "center",
    marginTop: 4,
    fontWeight: "600",
  },
  assignedCopy: { flex: 1, minWidth: 0, gap: 2 },
  assignedTitle: { fontSize: 16, lineHeight: 23, color: colors.primary, fontWeight: "600", flexShrink: 1 },
  assignedMeta: { fontSize: 13, lineHeight: 20, color: colors.muted, marginTop: 2 },
  assignedActions: { flexDirection: "row", gap: 6, marginTop: 8 },
  assignedCardLarge: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 20, marginBottom: 0, gap: 16, shadowColor: colors.primary, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  assignedTopRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  buildingThumb: { width: 56, height: 64, borderRadius: 12, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" },
  assignedTimeBox: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#EFF4F8", padding: 12, borderRadius: 14 },
  assignedTime: { color: colors.muted, fontSize: 13, lineHeight: 20, fontWeight: "400", flex: 1 },
  assignedBottomRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 12, borderTopWidth: 1, borderTopColor: "#E8EEF5", paddingTop: 16 },
  serviceMini: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
  assignedServiceText: { fontSize: 13, lineHeight: 20, color: colors.text, fontWeight: "500", flexShrink: 1 },
  upcomingButton: { backgroundColor: "#E9F1FB" },
  upcomingButtonText: { color: colors.muted },
  viewButton: { flexGrow: 1, flexBasis: 120, minHeight: 48, borderRadius: 999, borderWidth: 1, borderColor: colors.border, padding: 12, justifyContent: "center", alignItems: "center" },
  viewButtonText: { fontSize: 13, lineHeight: 20, color: colors.info, fontWeight: "600" },
  startButton: { flexGrow: 1, flexBasis: 120, minHeight: 48, borderRadius: 999, backgroundColor: colors.primary, padding: 12, justifyContent: "center", alignItems: "center" },
  startButtonText: { fontSize: 13, lineHeight: 20, color: colors.surface, fontWeight: "600" },
  serviceFlexibleCopy: { flex: 1, minWidth: 0, gap: 4 },
  servicePrimaryAction: { minHeight: 56, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, backgroundColor: colors.primary, borderRadius: 999, padding: 18, shadowColor: colors.primary, shadowOffset: { width: 0, height: 6 }, shadowRadius: 12, shadowOpacity: 0.18, elevation: 3 },
  serviceActionPressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
  serviceBodyText: { color: colors.muted, fontSize: 13, lineHeight: 21, flexShrink: 1 },
  serviceJobId: { color: colors.muted, fontSize: 12, lineHeight: 19, flexShrink: 1 },
  serviceCardHeading: { color: colors.primary, fontSize: 16, lineHeight: 23, fontWeight: "600" },
  serviceSectionHeading: { flexDirection: "row", alignItems: "center", gap: 12 },
  serviceBuildingHeading: { alignItems: "flex-start", gap: 8 },
  serviceInstructionCard: { backgroundColor: "#FFFBF2", borderWidth: 1, borderColor: "#F0E5CA", borderRadius: 22, padding: 20, gap: 14, borderLeftWidth: 4, borderLeftColor: colors.warn },
  serviceDirectionsCard: { backgroundColor: "#EAF2FF", borderWidth: 1, borderColor: "#D5E5FC", borderRadius: 22, padding: 22, gap: 16 },
  serviceLocationIcon: { width: 48, height: 48, backgroundColor: colors.surface, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  serviceDirectionsLink: { color: colors.info, fontSize: 13, lineHeight: 20, fontWeight: "600" },
  serviceContactCopy: { flex: 1, minWidth: 120, gap: 4 },
  serviceContactActions: { width: "100%", flexDirection: "row", flexWrap: "wrap", gap: 12, borderTopWidth: 1, borderTopColor: "#E8EEF5", paddingTop: 16 },
  serviceContactButton: { flexGrow: 1, flexBasis: 110, minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, padding: 12, borderRadius: 999, backgroundColor: "#EAF2FF" },
  serviceActionText: { color: colors.primary, fontSize: 13, lineHeight: 20, fontWeight: "600" },
  serviceMapButton: { minHeight: 48, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 999, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  flowHeader: { gap: 12 },
  flowHeaderRight: { alignItems: "flex-start", width: "100%", minWidth: 0, gap: 6 },
  callCircle: {
    minWidth: 42,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#E9F4FF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  callCircleText: { color: colors.info, fontSize: 12, fontWeight: "700" },
  stepTracker: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    backgroundColor: colors.surface,
    borderRadius: 18,
    paddingVertical: 20,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  flowStepItem: { alignItems: "center", flex: 1, minWidth: 0, gap: 10, paddingHorizontal: 3 },
  stepBubble: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#DDE5EF",
    alignItems: "center",
    justifyContent: "center",
  },
  stepBubbleActive: { backgroundColor: colors.action },
  stepBubbleCurrent: { backgroundColor: colors.primary },
  stepNumber: { color: colors.muted, fontWeight: "600", fontSize: 13 },
  stepBubbleText: { color: colors.surface, fontWeight: "700", fontSize: 12 },
  flowStepText: { fontSize: 12, lineHeight: 18, color: colors.muted, fontWeight: "500", textAlign: "center" },
  flowStepTextActive: { color: colors.primary },
  buildingCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 20,
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
  },
  buildingCardCompact: { padding: 20 },
  buildingImage: {
    width: 52,
    height: 56,
    borderRadius: 14,
    backgroundColor: "#EAF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  buildingGlyph: { fontSize: 36, color: colors.primary, fontWeight: "700" },
  buildingCopy: { flex: 1, minWidth: 0 },
  buildingTitle: { color: colors.primary, fontSize: 16, lineHeight: 23, fontWeight: "600", flexShrink: 1 },
  locationCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  fakeMapSmall: {
    height: 96,
    borderRadius: 8,
    backgroundColor: "#E5F0EA",
    overflow: "hidden",
    position: "relative",
  },
  mapLine: {
    position: "absolute",
    left: 30,
    right: 46,
    top: 46,
    height: 3,
    backgroundColor: colors.info,
    transform: [{ rotate: "-8deg" }],
  },
  mapPin: { position: "absolute", right: 62, top: 36, color: colors.danger, fontSize: 20 },
  mapLabel: {
    position: "absolute",
    right: 10,
    top: 28,
    color: colors.primary,
    fontSize: 12,
    fontWeight: "700",
  },
  mapOpen: {
    position: "absolute",
    right: 8,
    bottom: 8,
    color: colors.info,
    fontSize: 12,
    fontWeight: "700",
    backgroundColor: colors.surface,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  routeMap: {
    height: 210,
    borderRadius: 10,
    backgroundColor: "#E6EEF2",
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    position: "relative",
  },
  mapChipLeft: {
    position: "absolute",
    left: 42,
    top: 48,
    color: colors.info,
    backgroundColor: colors.surface,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    fontSize: 12,
    fontWeight: "700",
  },
  mapBlueDot: { position: "absolute", left: 38, top: 76, color: colors.info, fontSize: 28 },
  routeLine: {
    position: "absolute",
    left: 62,
    right: 66,
    top: 108,
    height: 4,
    backgroundColor: colors.info,
    transform: [{ rotate: "-10deg" }],
  },
  routeLineDotted: { borderStyle: "dotted", borderWidth: 2, borderColor: colors.info, backgroundColor: "transparent" },
  mapRedPin: { position: "absolute", right: 45, top: 112, color: colors.danger, fontSize: 28 },
  mapChipRight: {
    position: "absolute",
    right: 26,
    top: 88,
    color: colors.primary,
    backgroundColor: colors.surface,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    fontSize: 12,
    fontWeight: "700",
  },
  mapCity: { position: "absolute", left: "42%", top: 74, color: colors.muted, fontSize: 12 },
  mapCorner: { position: "absolute", right: 14, bottom: 14, color: colors.info, fontSize: 20 },
  routeStatsGrid: { flexDirection: "row", gap: 8 },
  routeStatCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
  },
  routeStatValue: { color: colors.primary, fontSize: 13, fontWeight: "700" },
  routeStatLabel: { color: colors.muted, fontSize: 12, marginTop: 3 },
  greenButton: { minHeight: 48, justifyContent: "center",
    backgroundColor: colors.action,
    borderRadius: 10,
    padding: 14,
    alignItems: "center",
    marginVertical: 5,
  },
  progressNotice: {
    backgroundColor: "#E7F5F3",
    borderRadius: 18,
    padding: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    borderWidth: 1,
    borderColor: "#CDE8E3",
  },
  progressNoticeTitle: { color: colors.teal, fontSize: 15, lineHeight: 22, fontWeight: "600" },
  progressNoticeText: { color: colors.teal, fontSize: 13, lineHeight: 21 },
  contactCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 24,
    padding: 22,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 16,
    shadowOpacity: 0.06,
    elevation: 2,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
  },
  profileAvatarSmall: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#E9F4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  completedHero: { alignItems: "center", paddingVertical: 18 },
  completedCheck: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: "#20C768",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  completedCheckText: { color: colors.surface, fontSize: 46, fontWeight: "700" },
  completedTitle: { color: colors.primary, fontSize: 24, fontWeight: "700" },
  ratingStars: {
    color: colors.yellow,
    fontSize: 26,
    textAlign: "center",
    marginVertical: 8,
    fontWeight: "700",
  },
  detailContent: { padding: 20, paddingBottom: 32, gap: 16, backgroundColor: colors.background, width: "100%", maxWidth: 760, alignSelf: "center" },
  detailHeading: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  detailId: { fontSize: 12, lineHeight: 18, color: colors.muted, flexShrink: 1, maxWidth: "100%" },
  detailIdentity: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  detailIdentityCopy: { flex: 1 },
  detailPlace: { fontSize: 14, color: colors.primary, fontWeight: "700" },
  detailMeta: { fontSize: 12, color: colors.muted, marginTop: 4 },
  liftIllustration: {
    width: 62,
    height: 54,
    backgroundColor: "#CFE0FF",
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  liftIllustrationRed: { backgroundColor: "#FFE0E0" },
  liftIllustrationGreen: { backgroundColor: "#D7F3E1" },
  liftIcon: { fontSize: 30, color: colors.info, fontWeight: "700" },
  detailTwoCol: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  detailRow: {
    flex: 1,
    minHeight: 58,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  detailRowIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#EAF2FF",
    color: colors.info,
    textAlign: "center",
    lineHeight: 26,
    fontWeight: "700",
  },
  detailWarningIcon: { backgroundColor: "#FFF5E6", color: colors.warn },
  detailRowCopy: { flex: 1 },
  detailRowLabel: { fontSize: 12, color: colors.muted },
  detailRowValue: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    marginTop: 3,
  },
  detailSectionTitle: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "700",
    marginTop: 4,
  },
  alertToolbar: {
    backgroundColor: "#EAF2FF",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  alertCount: { fontSize: 12, color: colors.primary, fontWeight: "700" },
  notificationCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  notificationUnread: { borderColor: "#BFD4F6", backgroundColor: "#FBFDFF" },
  notificationIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#EAF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationIconDanger: { backgroundColor: "#FFF0F0" },
  notificationIconText: { fontSize: 16, color: colors.info, fontWeight: "700" },
  notificationCopy: { flex: 1, minWidth: 0 },
  notificationTitle: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
    flex: 1,
  },
  notificationMessage: {
    fontSize: 12,
    lineHeight: 17,
    color: colors.muted,
    marginTop: 3,
  },
  notificationMeta: {
    fontSize: 12,
    color: colors.info,
    fontWeight: "600",
    marginTop: 6,
  },
  notificationTime: { fontSize: 12, color: colors.muted },
  unreadDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.info,
    marginTop: 5,
  },
  historyCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    flexDirection: "row",
    gap: 10,
  },
  historyIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: "#EAF7EF",
    alignItems: "center",
    justifyContent: "center",
  },
  historyIconText: { color: colors.action, fontWeight: "700", fontSize: 18 },
  historyCopy: { flex: 1, minWidth: 0 },
  historyMeta: { fontSize: 12, color: colors.muted, marginTop: 5 },
  journeyCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 14,
    marginVertical: 4,
  },
  journeySteps: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 12,
  },
  journeyStep: { flex: 1, alignItems: "center", gap: 5 },
  journeyDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ECEFF2",
    alignItems: "center",
    justifyContent: "center",
  },
  journeyDotActive: { backgroundColor: colors.action },
  journeyDotText: { fontSize: 14, color: colors.muted, fontWeight: "700" },
  journeyLabel: { fontSize: 12, color: colors.muted, textAlign: "center" },
  routeStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
    marginTop: 4,
  },
  routeStat: {
    flex: 1,
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    textAlign: "center",
  },
  mapButton: {
    backgroundColor: "#EAF2FF",
    borderRadius: 8,
    padding: 11,
    alignItems: "center",
    marginTop: 10,
  },
  mapButtonText: { color: colors.info, fontWeight: "700" },
  otpPanel: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: "#D2E1F5",
    shadowColor: colors.primary,
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    marginVertical: 4,
    gap: 14,
  },
  cashPanel: {
    backgroundColor: "#EAF7EF",
    borderRadius: 10,
    padding: 14,
    marginVertical: 4,
    gap: 4,
  },
  successHint: { color: colors.action, fontWeight: "600", marginTop: 6 },
  profileContent: { padding: 16, paddingBottom: 24, gap: 12, backgroundColor: colors.background },
  profileCard: {
    backgroundColor: "#EAF2FF",
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  profileEditCard: {
    backgroundColor: "#EAF2FF",
    borderRadius: 10,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  formCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
  },
  securityCard: {
    backgroundColor: "#EAF2FF",
    borderRadius: 10,
    padding: 14,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  securityIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#CFE0FF",
    color: colors.info,
    textAlign: "center",
    lineHeight: 34,
    fontWeight: "700",
    fontSize: 18,
  },
  helpTiles: { flexDirection: "row", gap: 8 },
  helpTile: {
    flex: 1,
    minHeight: 86,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 9,
  },
  helpTileIcon: { color: colors.info, fontWeight: "700", fontSize: 17 },
  helpTileTitle: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
    marginTop: 7,
  },
  helpTileMeta: {
    fontSize: 12,
    color: colors.muted,
    lineHeight: 17,
    marginTop: 3,
  },
  faqRow: {
    minHeight: 44,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#D1E0FA",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarText: { fontSize: 23 },
  profileCopy: { flex: 1 },
  profileName: { fontSize: 18, lineHeight: 26, color: colors.primary, fontWeight: "600" },
  profileEmail: { fontSize: 12, color: colors.muted, marginTop: 3 },
  profilePhone: { fontSize: 12, color: colors.muted, marginTop: 2 },
  editPill: { minHeight: 48, justifyContent: "center",
    backgroundColor: colors.info,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  editPillText: { fontSize: 12, color: colors.surface, fontWeight: "600" },
  settingsSection: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
    marginTop: 11,
    marginBottom: 2,
  },
  settingsRow: { backgroundColor: colors.surface, minHeight: 72, padding: 12, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: "row", alignItems: "center", gap: 12 },
  settingsRowSelected: {
    borderWidth: 1,
    borderColor: colors.info,
    borderRadius: 8,
  },
  settingsIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#EAF2FF",
    color: colors.info,
    textAlign: "center",
    lineHeight: 28,
    fontWeight: "700",
  },
  settingsCopy: { flex: 1 },
  settingsTitle: { fontSize: 15, lineHeight: 22, color: colors.primary, fontWeight: "700" },
  settingsSubtitle: { fontSize: 13, lineHeight: 20, color: colors.muted, flexShrink: 1 },
  logoutButton: { minHeight: 48,
    height: 42,
    borderWidth: 1,
    borderColor: colors.danger,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  logoutText: { color: colors.danger, fontSize: 12, fontWeight: "600" },
  welcomeSafe: {
    flex: 1,
    overflow: "hidden",
    backgroundColor: "#F7FAFF",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight ?? 0 : 0,
  },
  welcomeSubtitle: { color: "#667A98", fontFamily: "Georgia", fontSize: 16, lineHeight: 26, textAlign: "center" },
  welcomeBack: {
    minHeight: 42,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 24,
  },
  welcomeBackText: { color: colors.primary, fontWeight: "700", fontSize: 14 },
  signInContent: {
    flexGrow: 1,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    justifyContent: "center",
    padding: 30,
  },
  authSafe: { flex: 1, backgroundColor: colors.surface, paddingTop: Platform.OS === "android" ? StatusBar.currentHeight ?? 0 : 0 },
  authFrame: { flex: 1, width: "100%", maxWidth: 600, alignSelf: "center", backgroundColor: colors.surface },
  authTop: {
    minHeight: 72,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  authBack: { width: 52, height: 52, justifyContent: "center", alignItems: "flex-start" },
  authBackLink: { alignSelf: "center", minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 2, paddingHorizontal: 12 },
  brand: { flexDirection: "row", alignItems: "center", gap: 6 },
  brandMark: {
    fontSize: 33,
    color: colors.yellow,
    fontWeight: "700",
    transform: [{ rotate: "180deg" }],
  },
  brandName: {
    fontSize: 17,
    color: colors.primary,
    fontWeight: "700",
    letterSpacing: 1,
  },
  brandSub: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
    letterSpacing: 1.4,
  },
  stepText: {
    width: 86,
    textAlign: "right",
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
  },
  stepper: {
    flexDirection: "row",
    paddingHorizontal: 18,
    paddingBottom: 18,
    justifyContent: "space-between",
  },
  stepItem: { alignItems: "center", flex: 1 },
  stepDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#E6EBF2",
    alignItems: "center",
    justifyContent: "center",
  },
  stepDotActive: { backgroundColor: colors.info },
  stepDotText: { fontSize: 12, color: colors.primary, fontWeight: "600" },
  stepLabel: {
    fontSize: 10,
    lineHeight: 14,
    color: colors.muted,
    marginTop: 5,
    textAlign: "center",
    paddingHorizontal: 2,
  },
  authContent: { width: "100%", maxWidth: 520, alignSelf: "center", paddingHorizontal: 24, paddingTop: 8, paddingBottom: 36 },
  authTitle: {
    fontSize: 24,
    lineHeight: 30,
    color: colors.primary,
    fontWeight: "700",
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 20,
    marginBottom: 22,
  },
  authSectionTitle: {
    fontSize: 18,
    color: colors.primary,
    fontWeight: "700",
    marginTop: 4,
  },
  authHelper: {
    fontSize: 12,
    color: colors.muted,
    marginBottom: 12,
    lineHeight: 17,
  },
  authField: { marginBottom: 14 },
  fieldLabel: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    marginBottom: 7,
  },
  authInput: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  authSelectRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  authOptions: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.surface, marginTop: 4, overflow: "hidden" },
  authOption: { minHeight: 48, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.border },
  fieldPlaceholder: { color: colors.muted, fontSize: 12 },
  fieldValue: { color: colors.text, fontSize: 12 },
  selectChevron: {
    position: "absolute",
    right: 12,
    top: 12,
    color: colors.muted,
    fontSize: 16,
  },
  infoStrip: {
    backgroundColor: "#EAF2FF",
    borderRadius: 8,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 8,
  },
  infoIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.info,
    color: colors.surface,
    textAlign: "center",
    lineHeight: 20,
    fontWeight: "700",
  },
  infoText: { fontSize: 12, color: colors.muted, lineHeight: 17, flex: 1 },
  authButton: {
    minHeight: 54,
    borderRadius: 12,
    backgroundColor: colors.info,
    marginTop: 18,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  authButtonText: { color: colors.surface, fontWeight: "600", fontSize: 13 },
  authButtonSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.info,
  },
  authButtonSecondaryText: {
    color: colors.info,
    fontWeight: "600",
    fontSize: 13,
    textAlign: "center",
    flex: 1,
  },
  authFooter: {
    textAlign: "center",
    color: colors.muted,
    fontSize: 12,
    marginTop: 20,
  },
  authLink: { color: colors.info, fontWeight: "600" },
  signInHero: { alignItems: "center", marginBottom: 18 },
  signInIcon: { width: 68, height: 68, borderRadius: 20, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  authError: {
    color: colors.danger,
    fontSize: 12,
    lineHeight: 17,
    marginVertical: 6,
  },
  fieldValueText: { color: colors.text },
  segmentRow: { flexDirection: "row", gap: 8, marginBottom: 10 },
  segment: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  segmentActive: { borderColor: colors.info, backgroundColor: "#EAF2FF" },
  segmentText: { fontSize: 12, color: colors.primary, fontWeight: "700" },
  otpIllustration: {
    height: 130,
    width: 130,
    borderRadius: 65,
    backgroundColor: "#EAF2FF",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
    marginBottom: 18,
  },
  otpPhone: { fontSize: 76, color: "#8FA5D5", lineHeight: 107 },
  otpBubble: {
    position: "absolute",
    right: 18,
    top: 44,
    backgroundColor: colors.info,
    color: colors.surface,
    borderRadius: 8,
    padding: 9,
    fontWeight: "700",
  },
  otpTitle: {
    fontSize: 20,
    color: colors.primary,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 8,
  },
  otpPhoneText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 10,
  },
  otpInput: {
    height: 56,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    textAlign: "center",
    letterSpacing: 8,
    fontSize: 22,
    color: colors.text,
    marginVertical: 10,
  },
  otpHint: {
    fontSize: 12,
    color: colors.muted,
    textAlign: "center",
    marginTop: 18,
  },
  otpResend: {
    fontSize: 12,
    color: colors.muted,
    textAlign: "center",
    marginTop: 8,
  },
  documentRow: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 7,
  },
  documentIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#EAF2FF",
    color: colors.info,
    textAlign: "center",
    lineHeight: 32,
    fontWeight: "700",
  },
  documentCopy: { flex: 1 },
  documentTitle: { fontSize: 12, color: colors.primary, fontWeight: "600" },
  documentMeta: { fontSize: 12, color: colors.muted, marginTop: 2 },
  uploadAction: { color: colors.info, fontSize: 12, fontWeight: "600" },
  uploaded: {
    color: colors.action,
    backgroundColor: "#EAF7EF",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "600",
  },
  reviewCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  reviewTitle: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: "700",
    marginBottom: 8,
  },
  reviewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 4,
  },
  reviewLabel: { fontSize: 12, color: colors.muted, flex: 1 },
  reviewValue: {
    fontSize: 12,
    color: colors.text,
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  successIcon: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: "#EAF7EF",
    color: colors.action,
    textAlign: "center",
    lineHeight: 92,
    fontSize: 58,
    fontWeight: "700",
    alignSelf: "center",
    marginTop: 38,
    marginBottom: 18,
  },
  successTitle: {
    fontSize: 24,
    color: colors.primary,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 8,
  },
  successText: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 20,
    textAlign: "center",
    marginBottom: 20,
  },
  screenTopRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 12 },
  filterChipButton: { minHeight: 48, justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.info,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: colors.surface,
  },
  segmentedTabs: { flexDirection: "row", flexWrap: "wrap", gap: 4, backgroundColor: "#EAF1FB", padding: 4, borderRadius: 12, marginBottom: 12 },
  segmentTab: { flexGrow: 1, flexBasis: 120, minHeight: 44, padding: 8, alignItems: "center", justifyContent: "center", borderRadius: 8 },
  segmentTabActive: { backgroundColor: colors.info },
  segmentTabText: { color: colors.primary, fontSize: 12, fontWeight: "600", textAlign: "center" },
  segmentTabTextActive: { color: colors.surface },
  historyListRow: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    flexDirection: "row",
    gap: 10,
  },
  historyIconBox: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: "#EAF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  historyJobId: { color: colors.primary, fontSize: 13, fontWeight: "700", flexShrink: 1 },
  historyBuilding: { color: colors.primary, fontSize: 12, fontWeight: "600", marginTop: 2 },
  historyMetaRow: { flexDirection: "row", justifyContent: "space-between", gap: 8, marginTop: 7 },
  groupTitle: { color: colors.primary, fontSize: 12, fontWeight: "700", marginVertical: 8 },
  alertRow: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  alertIcon: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" },
  alertIconBlue: { backgroundColor: "#EAF2FF" },
  alertIconDanger: { backgroundColor: "#FFE8E8" },
  alertIconAmber: { backgroundColor: "#FFF4D8" },
  alertIconMuted: { backgroundColor: "#EEF2F7" },
  alertIconText: { color: colors.primary, fontSize: 14, fontWeight: "700" },
  profileHeaderCard: {
    backgroundColor: "#F1F6FF",
    borderRadius: 10,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#DDEBFF",
    marginVertical: 10,
  },
  profilePhotoLarge: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#DDEBFA",
    alignItems: "center",
    justifyContent: "center",
  },
  changePhotoButton: {
    borderWidth: 1,
    borderColor: colors.info,
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: colors.surface,
  },
  twoColumnForm: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
  },
  twoColumnFormInner: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  formCardSoft: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, gap: 10 },
  profileField: { flexGrow: 1, flexBasis: 220, minWidth: 0, gap: 8 },
  profileFieldWide: { flexBasis: "100%" },
  profileFieldLabel: { color: colors.primary, fontSize: 13, fontWeight: "700" },
  profileFieldInput: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 12, color: colors.text, fontSize: 15, backgroundColor: colors.surface },
  profileFieldDisabled: { backgroundColor: "#F4F7FB", color: colors.muted },
  securityCardBlue: { backgroundColor: "#EFF6FF", borderRadius: 10, padding: 12, flexDirection: "row", alignItems: "center", gap: 12, marginVertical: 10 },
  securityLock: { width: 52, height: 52, borderRadius: 26, backgroundColor: colors.info, alignItems: "center", justifyContent: "center" },
  passwordInputWrap: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", paddingHorizontal: 12, gap: 8 },
  passwordLock: { color: colors.primary, fontWeight: "700" },
  passwordInput: { flex: 1, color: colors.text, fontSize: 12 },
  passwordEye: { color: colors.muted, fontWeight: "700" },
  passwordRulesCard: { backgroundColor: "#EFF6FF", borderRadius: 10, padding: 12, marginVertical: 10 },
  ruleText: { color: colors.primary, fontSize: 12, marginTop: 6 },
  searchInput: { height: 40, borderRadius: 8, backgroundColor: "#EEF4FB", paddingHorizontal: 12, color: colors.text, marginVertical: 10 },
  helpTilesFour: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 16 },
  supportTile: { flexGrow: 1, flexBasis: 140, minHeight: 112, padding: 16, alignItems: "center", borderRadius: 12 },
  supportTileblue: { backgroundColor: "#EAF2FF" },
  supportTilegreen: { backgroundColor: "#EAF8EF" },
  supportTilered: { backgroundColor: "#FFEDED" },
  supportTilepurple: { backgroundColor: "#E7F5F3" },
  supportTileIcon: { color: colors.info, fontSize: 17, fontWeight: "700" },
  supportTileTitle: { color: colors.primary, fontSize: 12, fontWeight: "700", textAlign: "center", marginTop: 5 },
  supportTileMeta: { color: colors.muted, fontSize: 12, textAlign: "center", lineHeight: 17, marginTop: 3 },
  supportContact: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  supportContactDanger: { backgroundColor: "#FFF2F2", borderColor: "#FFD0D0" },
  supportContactIcon: { width: 30, textAlign: "center", color: colors.info, fontWeight: "700" },
  supportHours: { backgroundColor: "#EAF2FF", borderRadius: 10, padding: 10, flexDirection: "row", alignItems: "center", gap: 8, marginTop: 4 },
  logoutRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
});
