package com.valor.service.impl;
import com.valor.dto.technician.TechnicianDtos.*;import com.valor.entity.*;import com.valor.enums.*;import com.valor.exception.NotFoundException;import com.valor.repository.*;import com.valor.service.TechnicianService;import jakarta.transaction.Transactional;import org.springframework.stereotype.Service;import java.time.Instant;import java.util.*;
@Service @Transactional public class TechnicianServiceImpl implements TechnicianService {
 private final ServiceRequestRepository requests;private final TechnicianAssignmentRepository assignments;private final ServiceVisitRepository visits;private final StatusHistoryRepository history;
 public TechnicianServiceImpl(ServiceRequestRepository requests,TechnicianAssignmentRepository assignments,ServiceVisitRepository visits,StatusHistoryRepository history){this.requests=requests;this.assignments=assignments;this.visits=visits;this.history=history;}
 public Dashboard dashboard(UUID id){var jobs=jobs(id);return new Dashboard(jobs.stream().filter(j->j.status()==ServiceRequestStatus.ASSIGNED).count(),jobs.stream().filter(j->j.status()==ServiceRequestStatus.OPEN).count(),jobs.stream().filter(j->j.status()==ServiceRequestStatus.IN_PROGRESS).count(),jobs.stream().filter(j->j.status()==ServiceRequestStatus.COMPLETED).count(),jobs.stream().filter(j->j.priority()==Priority.EMERGENCY).count());}
 public List<JobSummary> jobs(UUID id){return requests.findAssignedTo(id,EnumSet.allOf(ServiceRequestStatus.class)).stream().map(this::summary).toList();}
 public JobDetail job(UUID id,UUID requestId){var r=requestForTechnician(id,requestId);return new JobDetail(r.getId(),r.getTicketNumber(),r.getStatus(),r.getPriority(),r.getCustomer().getFullName(),r.getCustomer().getPhone(),r.getLift().getBuildingName(),r.getLift().getLiftNumber(),r.getLift().getAddress(),r.getIssueType(),r.getDescription(),r.getPreferredVisitAt());}
 public JobSummary accept(UUID id,UUID requestId){var r=requestForTechnician(id,requestId);if(r.getStatus()!=ServiceRequestStatus.ASSIGNED)throw new IllegalStateException("Only assigned requests can be accepted.");transition(r,id,ServiceRequestStatus.ACCEPTED,"Job accepted");assignments.findByServiceRequestIdAndTechnicianId(requestId,id).ifPresent(a->a.setAcceptedAt(Instant.now()));return summary(r);}
 public JobSummary updateStatus(UUID id,UUID requestId,UpdateStatusRequest change){var r=requestForTechnician(id,requestId);if(change.status()==ServiceRequestStatus.COMPLETED)throw new IllegalStateException("Submit the service report to complete a request.");transition(r,id,change.status(),change.note());if(change.status()==ServiceRequestStatus.ON_SITE)assignments.findByServiceRequestIdAndTechnicianId(requestId,id).ifPresent(a->a.setArrivedAt(Instant.now()));return summary(r);}
 public ServiceRequest requestForTechnician(UUID id,UUID requestId){assignments.findByServiceRequestIdAndTechnicianId(requestId,id).orElseThrow(()->new NotFoundException("Assigned request not found."));return requests.findById(requestId).orElseThrow(()->new NotFoundException("Service request not found."));}
 public void saveDiagnosis(UUID id,UUID requestId,DiagnosisRequest input){var r=requestForTechnician(id,requestId);var v=visits.findByServiceRequestId(requestId).orElseGet(()->{var x=new ServiceVisit();x.setServiceRequest(r);x.setTechnician(assignments.findByServiceRequestIdAndTechnicianId(requestId,id).orElseThrow().getTechnician());x.setStartedAt(Instant.now());return x;});v.setDiagnosis(input.diagnosis());visits.save(v);if(r.getStatus()!=ServiceRequestStatus.IN_PROGRESS)transition(r,id,ServiceRequestStatus.IN_PROGRESS,"Diagnosis recorded");}
 public void submitReport(UUID id,UUID requestId,ReportRequest input){var r=requestForTechnician(id,requestId);var v=visits.findByServiceRequestId(requestId).orElseThrow(()->new IllegalStateException("A diagnosis must be recorded before completing service."));v.setServiceReport(input.report());v.setCustomerSignaturePath(input.signatureStorageKey());v.setEndedAt(Instant.now());transition(r,id,ServiceRequestStatus.COMPLETED,"Service report submitted");r.setCompletedAt(Instant.now());}
 private void transition(ServiceRequest r,UUID technicianId,ServiceRequestStatus next,String note){if(!allowed(r.getStatus(),next))throw new IllegalStateException("Invalid status transition from "+r.getStatus()+" to "+next+".");var entry=new StatusHistory();entry.setServiceRequest(r);entry.setChangedBy(assignments.findByServiceRequestIdAndTechnicianId(r.getId(),technicianId).orElseThrow().getTechnician());entry.setFromStatus(r.getStatus());entry.setToStatus(next);entry.setNote(note);history.save(entry);r.setStatus(next);}
 private boolean allowed(ServiceRequestStatus current,ServiceRequestStatus next){return switch(current){case ASSIGNED->next==ServiceRequestStatus.ACCEPTED||next==ServiceRequestStatus.CANCELLED;case ACCEPTED->next==ServiceRequestStatus.ON_THE_WAY||next==ServiceRequestStatus.CANCELLED;case ON_THE_WAY->next==ServiceRequestStatus.ON_SITE||next==ServiceRequestStatus.CANCELLED;case ON_SITE->next==ServiceRequestStatus.IN_PROGRESS||next==ServiceRequestStatus.CANCELLED;case IN_PROGRESS->next==ServiceRequestStatus.WAITING_FOR_PARTS||next==ServiceRequestStatus.TESTING||next==ServiceRequestStatus.CANCELLED;case WAITING_FOR_PARTS->next==ServiceRequestStatus.IN_PROGRESS||next==ServiceRequestStatus.CANCELLED;case TESTING->next==ServiceRequestStatus.IN_PROGRESS||next==ServiceRequestStatus.CANCELLED;default->false;};}
 private JobSummary summary(ServiceRequest r){return new JobSummary(r.getId(),r.getTicketNumber(),r.getCustomer().getFullName(),r.getLift().getBuildingName(),r.getLift().getLiftNumber(),r.getIssueType(),r.getPriority(),r.getStatus(),r.getPreferredVisitAt());}
}
